export interface ReadingTest {
  id: string;
  name: string;
  title: string;
  slug: string;
  filename: string;
  category: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  duration: number;
  questionCount: number;
}

export const READING_CATEGORIES = ["Academic","Cambridge","Mock","Passage 1","Passage 2","Passage 3"];

export const READING_TESTS: ReadingTest[] = [
  {
    "id": "1",
    "name": "200_Years_of_Australian_Landscapes",
    "title": "200_Years_of_Australian_Landscapes",
    "slug": "200-years-of-australian-landscapes",
    "filename": "200_Years_of_Australian_Landscapes.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "2",
    "name": "airborne_dentists",
    "title": "airborne_dentists",
    "slug": "airborne-dentists",
    "filename": "airborne_dentists.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "3",
    "name": "Ancient Storytelling",
    "title": "Ancient Storytelling",
    "slug": "ancient-storytelling",
    "filename": "Ancient Storytelling.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "4",
    "name": "Antarctica_Passage_1",
    "title": "Antarctica_Passage_1",
    "slug": "antarctica-passage-1",
    "filename": "Antarctica_Passage_1.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "5",
    "name": "Australian Artist Margaret Preston",
    "title": "Australian Artist Margaret Preston",
    "slug": "australian-artist-margaret-preston",
    "filename": "Australian Artist Margaret Preston.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "6",
    "name": "Authentic Reading Mock 1",
    "title": "Authentic Reading Mock 1",
    "slug": "authentic-reading-mock-1",
    "filename": "Authentic Reading Mock 1 .html",
    "category": "Mock",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "7",
    "name": "Authentic Reading Mock 14 (1)",
    "title": "Authentic Reading Mock 14 (1)",
    "slug": "authentic-reading-mock-14-1",
    "filename": "Authentic Reading Mock 14 (1).html",
    "category": "Mock",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "8",
    "name": "Authentic Reading Mock 14",
    "title": "Authentic Reading Mock 14",
    "slug": "authentic-reading-mock-14",
    "filename": "Authentic Reading Mock 14 .html",
    "category": "Mock",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "9",
    "name": "Authentic Reading Mock 15",
    "title": "Authentic Reading Mock 15",
    "slug": "authentic-reading-mock-15",
    "filename": "Authentic Reading Mock 15 .html",
    "category": "Mock",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "10",
    "name": "Authentic Reading Mock 2",
    "title": "Authentic Reading Mock 2",
    "slug": "authentic-reading-mock-2",
    "filename": "Authentic Reading Mock 2 .html",
    "category": "Mock",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "11",
    "name": "Authentic Reading Mock (1)",
    "title": "Authentic Reading Mock (1)",
    "slug": "authentic-reading-mock-1",
    "filename": "Authentic Reading Mock (1).html",
    "category": "Mock",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "12",
    "name": "Authentic Reading Mock (2)",
    "title": "Authentic Reading Mock (2)",
    "slug": "authentic-reading-mock-2",
    "filename": "Authentic Reading Mock (2).html",
    "category": "Mock",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "13",
    "name": "Authentic Reading Mock (3)",
    "title": "Authentic Reading Mock (3)",
    "slug": "authentic-reading-mock-3",
    "filename": "Authentic Reading Mock (3).html",
    "category": "Mock",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "14",
    "name": "Authentic Reading Mock",
    "title": "Authentic Reading Mock",
    "slug": "authentic-reading-mock",
    "filename": "Authentic Reading Mock .html",
    "category": "Mock",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "15",
    "name": "Authentic Reading Mock Passage 3",
    "title": "Authentic Reading Mock Passage 3",
    "slug": "authentic-reading-mock-passage-3",
    "filename": "Authentic Reading Mock Passage 3 .html",
    "category": "Mock",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "16",
    "name": "back to wild przewalski horse reading cdi",
    "title": "back to wild przewalski horse reading cdi",
    "slug": "back-to-wild-przewalski-horse-reading-cdi",
    "filename": "back to wild przewalski horse reading cdi.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "17",
    "name": "Barcode_",
    "title": "Barcode_",
    "slug": "barcode",
    "filename": "Barcode_.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "18",
    "name": "Bees and Pollination",
    "title": "Bees and Pollination",
    "slug": "bees-and-pollination",
    "filename": "Bees and Pollination.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "19",
    "name": "Biological_Control_",
    "title": "Biological_Control_",
    "slug": "biological-control",
    "filename": "Biological_Control_.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "20",
    "name": "bipedalism reading cdi",
    "title": "bipedalism reading cdi",
    "slug": "bipedalism-reading-cdi",
    "filename": "bipedalism reading cdi.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "21",
    "name": "Bird Migration 2 ()",
    "title": "Bird Migration 2 ()",
    "slug": "bird-migration-2",
    "filename": "Bird Migration 2 ().html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "22",
    "name": "Bird_Migration",
    "title": "Bird_Migration",
    "slug": "bird-migration",
    "filename": "Bird_Migration.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "23",
    "name": "Burgess_Shale_",
    "title": "Burgess_Shale_",
    "slug": "burgess-shale",
    "filename": "Burgess_Shale_.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "24",
    "name": "Cambridge 21 Test 1 Reading (1)",
    "title": "Cambridge 21 Test 1 Reading (1)",
    "slug": "cambridge-21-test-1-reading-1",
    "filename": "Cambridge 21 Test 1 Reading (1).html",
    "category": "Cambridge",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "25",
    "name": "Cambridge 21 Test 1 Reading",
    "title": "Cambridge 21 Test 1 Reading",
    "slug": "cambridge-21-test-1-reading",
    "filename": "Cambridge 21 Test 1 Reading .html",
    "category": "Cambridge",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "26",
    "name": "Cambridge 21 Test 2 Reading",
    "title": "Cambridge 21 Test 2 Reading",
    "slug": "cambridge-21-test-2-reading",
    "filename": "Cambridge 21 Test 2 Reading .html",
    "category": "Cambridge",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "27",
    "name": "Cambridge 21 Test 3 Reading",
    "title": "Cambridge 21 Test 3 Reading",
    "slug": "cambridge-21-test-3-reading",
    "filename": "Cambridge 21 Test 3 Reading .html",
    "category": "Cambridge",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "28",
    "name": "Cambridge 21 Test 4 Reading",
    "title": "Cambridge 21 Test 4 Reading",
    "slug": "cambridge-21-test-4-reading",
    "filename": "Cambridge 21 Test 4 Reading .html",
    "category": "Cambridge",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "29",
    "name": "Can All Reading Help Children",
    "title": "Can All Reading Help Children",
    "slug": "can-all-reading-help-children",
    "filename": "Can All Reading Help Children.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "30",
    "name": "Childs_Play_in_Medieval_England",
    "title": "Childs_Play_in_Medieval_England",
    "slug": "childs-play-in-medieval-england",
    "filename": "Childs_Play_in_Medieval_England.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "31",
    "name": "chilli peppers reading cdi",
    "title": "chilli peppers reading cdi",
    "slug": "chilli-peppers-reading-cdi",
    "filename": "chilli peppers reading cdi.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "32",
    "name": "Chinese_Chariots_",
    "title": "Chinese_Chariots_",
    "slug": "chinese-chariots",
    "filename": "Chinese_Chariots_.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "33",
    "name": "Communicating Conflict",
    "title": "Communicating Conflict",
    "slug": "communicating-conflict",
    "filename": "Communicating Conflict.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "34",
    "name": "Dead_Sea_Scrolls_",
    "title": "Dead_Sea_Scrolls_",
    "slug": "dead-sea-scrolls",
    "filename": "Dead_Sea_Scrolls_.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "35",
    "name": "E-training",
    "title": "E-training",
    "slug": "e-training",
    "filename": "E-training.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "36",
    "name": "Easter_Island_",
    "title": "Easter_Island_",
    "slug": "easter-island",
    "filename": "Easter_Island_.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "37",
    "name": "Education Philosophy",
    "title": "Education Philosophy",
    "slug": "education-philosophy",
    "filename": "Education Philosophy.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "38",
    "name": "Emperor_Penguins_",
    "title": "Emperor_Penguins_",
    "slug": "emperor-penguins",
    "filename": "Emperor_Penguins_.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "39",
    "name": "Flower Power",
    "title": "Flower Power",
    "slug": "flower-power",
    "filename": "Flower Power.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "40",
    "name": "Footprints_in_the_Muds_of_Time",
    "title": "Footprints_in_the_Muds_of_Time",
    "slug": "footprints-in-the-muds-of-time",
    "filename": "Footprints_in_the_Muds_of_Time.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "41",
    "name": "Full mock 3",
    "title": "Full mock 3",
    "slug": "full-mock-3",
    "filename": "Full mock 3.html",
    "category": "Mock",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "42",
    "name": "Full mock_2",
    "title": "Full mock_2",
    "slug": "full-mock-2",
    "filename": "Full mock_2.html",
    "category": "Mock",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "43",
    "name": "Future of Food Packaging - Passage 2",
    "title": "Future of Food Packaging - Passage 2",
    "slug": "future-of-food-packaging-passage-2",
    "filename": "Future of Food Packaging - Passage 2 .html",
    "category": "Passage 2",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "44",
    "name": "Great_Migrations_",
    "title": "Great_Migrations_",
    "slug": "great-migrations",
    "filename": "Great_Migrations_.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "45",
    "name": "Hollywood_",
    "title": "Hollywood_",
    "slug": "hollywood",
    "filename": "Hollywood_.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "46",
    "name": "IQ_Scores",
    "title": "IQ_Scores",
    "slug": "iq-scores",
    "filename": "IQ_Scores.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "47",
    "name": "John_Ray_and_the_Study_of_Plants",
    "title": "John_Ray_and_the_Study_of_Plants",
    "slug": "john-ray-and-the-study-of-plants",
    "filename": "John_Ray_and_the_Study_of_Plants.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "48",
    "name": "Keystone species (1)",
    "title": "Keystone species (1)",
    "slug": "keystone-species-1",
    "filename": "Keystone species (1).html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "49",
    "name": "Learning second language",
    "title": "Learning second language",
    "slug": "learning-second-language",
    "filename": "Learning second language.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "50",
    "name": "Lever Brothers Sunlight Soap ()",
    "title": "Lever Brothers Sunlight Soap ()",
    "slug": "lever-brothers-sunlight-soap",
    "filename": "Lever Brothers Sunlight Soap ().html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "51",
    "name": "Life on Mars (1)",
    "title": "Life on Mars (1)",
    "slug": "life-on-mars-1",
    "filename": "Life on Mars (1).html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "52",
    "name": "Life_Casting_and_Art_",
    "title": "Life_Casting_and_Art_",
    "slug": "life-casting-and-art",
    "filename": "Life_Casting_and_Art_.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "53",
    "name": "LONGAEVA Ancient Bristlecone Pine",
    "title": "LONGAEVA Ancient Bristlecone Pine",
    "slug": "longaeva-ancient-bristlecone-pine",
    "filename": "LONGAEVA Ancient Bristlecone Pine.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "54",
    "name": "Mammoth Kill 2 ()",
    "title": "Mammoth Kill 2 ()",
    "slug": "mammoth-kill-2",
    "filename": "Mammoth Kill 2 ().html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "55",
    "name": "margaret mahy",
    "title": "margaret mahy",
    "slug": "margaret-mahy",
    "filename": "margaret mahy.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "56",
    "name": "Marketing_and_Mind_Control",
    "title": "Marketing_and_Mind_Control",
    "slug": "marketing-and-mind-control",
    "filename": "Marketing_and_Mind_Control.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "57",
    "name": "Mark_Strizic",
    "title": "Mark_Strizic",
    "slug": "mark-strizic",
    "filename": "Mark_Strizic.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "58",
    "name": "Museums and Family Visitors in Australia",
    "title": "Museums and Family Visitors in Australia",
    "slug": "museums-and-family-visitors-in-australia",
    "filename": "Museums and Family Visitors in Australia.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "59",
    "name": "Music Language We All Speak",
    "title": "Music Language We All Speak",
    "slug": "music-language-we-all-speak",
    "filename": "Music Language We All Speak.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "60",
    "name": "New Zealand Seaweed",
    "title": "New Zealand Seaweed",
    "slug": "new-zealand-seaweed",
    "filename": "New Zealand Seaweed.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "61",
    "name": "Optimism and Health Reading",
    "title": "Optimism and Health Reading",
    "slug": "optimism-and-health-reading",
    "filename": "Optimism and Health Reading.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "62",
    "name": "Passage 1 A Look at the History of Poetry",
    "title": "Passage 1 A Look at the History of Poetry",
    "slug": "passage-1-a-look-at-the-history-of-poetry",
    "filename": "Passage 1 A Look at the History of Poetry.html",
    "category": "Passage 1",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "63",
    "name": "Passage 1 Dyes and Fabric Dyeing",
    "title": "Passage 1 Dyes and Fabric Dyeing",
    "slug": "passage-1-dyes-and-fabric-dyeing",
    "filename": "Passage 1 Dyes and Fabric Dyeing.html",
    "category": "Passage 1",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "64",
    "name": "Passage 1 Flying the Coast",
    "title": "Passage 1 Flying the Coast",
    "slug": "passage-1-flying-the-coast",
    "filename": "Passage 1 Flying the Coast.html",
    "category": "Passage 1",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "65",
    "name": "Passage 1 In Deep Water",
    "title": "Passage 1 In Deep Water",
    "slug": "passage-1-in-deep-water",
    "filename": "Passage 1 In Deep Water.html",
    "category": "Passage 1",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "66",
    "name": "Passage 1 Museums and Family Visitors in Australia (1)",
    "title": "Passage 1 Museums and Family Visitors in Australia (1)",
    "slug": "passage-1-museums-and-family-visitors-in-australia-1",
    "filename": "Passage 1 Museums and Family Visitors in Australia (1).html",
    "category": "Passage 1",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "67",
    "name": "Passage 1 Museums and Family Visitors in Australia",
    "title": "Passage 1 Museums and Family Visitors in Australia",
    "slug": "passage-1-museums-and-family-visitors-in-australia",
    "filename": "Passage 1 Museums and Family Visitors in Australia.html",
    "category": "Passage 1",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "68",
    "name": "Passage 1 The Media Literacy of Children",
    "title": "Passage 1 The Media Literacy of Children",
    "slug": "passage-1-the-media-literacy-of-children",
    "filename": "Passage 1 The Media Literacy of Children.html",
    "category": "Passage 1",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "69",
    "name": "Passage 1 The Origin of Paper",
    "title": "Passage 1 The Origin of Paper",
    "slug": "passage-1-the-origin-of-paper",
    "filename": "Passage 1 The Origin of Paper.html",
    "category": "Passage 1",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "70",
    "name": "Passage 1 The Tuatara of New Zealand",
    "title": "Passage 1 The Tuatara of New Zealand",
    "slug": "passage-1-the-tuatara-of-new-zealand",
    "filename": "Passage 1 The Tuatara of New Zealand.html",
    "category": "Passage 1",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "71",
    "name": "Passage 1 Thomas Cole American Nature Painter",
    "title": "Passage 1 Thomas Cole American Nature Painter",
    "slug": "passage-1-thomas-cole-american-nature-painter",
    "filename": "Passage 1 Thomas Cole American Nature Painter.html",
    "category": "Passage 1",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "72",
    "name": "Passage 2 Creative Problem-Solving (1)",
    "title": "Passage 2 Creative Problem-Solving (1)",
    "slug": "passage-2-creative-problem-solving-1",
    "filename": "Passage 2 Creative Problem-Solving (1).html",
    "category": "Passage 2",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "73",
    "name": "Passage 2 Creative Problem-Solving",
    "title": "Passage 2 Creative Problem-Solving",
    "slug": "passage-2-creative-problem-solving",
    "filename": "Passage 2 Creative Problem-Solving.html",
    "category": "Passage 2",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "74",
    "name": "Passage 2 Growing Food in Cities",
    "title": "Passage 2 Growing Food in Cities",
    "slug": "passage-2-growing-food-in-cities",
    "filename": "Passage 2 Growing Food in Cities.html",
    "category": "Passage 2",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "75",
    "name": "Passage 2 Homo ergaster (1)",
    "title": "Passage 2 Homo ergaster (1)",
    "slug": "passage-2-homo-ergaster-1",
    "filename": "Passage 2 Homo ergaster (1).html",
    "category": "Passage 2",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "76",
    "name": "Passage 2 Homo ergaster",
    "title": "Passage 2 Homo ergaster",
    "slug": "passage-2-homo-ergaster",
    "filename": "Passage 2 Homo ergaster.html",
    "category": "Passage 2",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "77",
    "name": "Passage 2 How the Petri dish supports scientific advances",
    "title": "Passage 2 How the Petri dish supports scientific advances",
    "slug": "passage-2-how-the-petri-dish-supports-scientific-advances",
    "filename": "Passage 2 How the Petri dish supports scientific advances.html",
    "category": "Passage 2",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "78",
    "name": "Passage 2 Keeping an Eye on Shoppers",
    "title": "Passage 2 Keeping an Eye on Shoppers",
    "slug": "passage-2-keeping-an-eye-on-shoppers",
    "filename": "Passage 2 Keeping an Eye on Shoppers.html",
    "category": "Passage 2",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "79",
    "name": "Passage 2 Keeping the Water Away",
    "title": "Passage 2 Keeping the Water Away",
    "slug": "passage-2-keeping-the-water-away",
    "filename": "Passage 2 Keeping the Water Away.html",
    "category": "Passage 2",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "80",
    "name": "Passage 2 The Fascinating World of Attine Ants",
    "title": "Passage 2 The Fascinating World of Attine Ants",
    "slug": "passage-2-the-fascinating-world-of-attine-ants",
    "filename": "Passage 2 The Fascinating World of Attine Ants.html",
    "category": "Passage 2",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "81",
    "name": "Passage 2 The Fashion Industry",
    "title": "Passage 2 The Fashion Industry",
    "slug": "passage-2-the-fashion-industry",
    "filename": "Passage 2 The Fashion Industry.html",
    "category": "Passage 2",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "82",
    "name": "Passage 2 The Internal Body Clock",
    "title": "Passage 2 The Internal Body Clock",
    "slug": "passage-2-the-internal-body-clock",
    "filename": "Passage 2 The Internal Body Clock.html",
    "category": "Passage 2",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "83",
    "name": "Passage 2 The Power of Music",
    "title": "Passage 2 The Power of Music",
    "slug": "passage-2-the-power-of-music",
    "filename": "Passage 2 The Power of Music.html",
    "category": "Passage 2",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "84",
    "name": "Passage 2 The Tasmanian Tiger",
    "title": "Passage 2 The Tasmanian Tiger",
    "slug": "passage-2-the-tasmanian-tiger",
    "filename": "Passage 2 The Tasmanian Tiger.html",
    "category": "Passage 2",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "85",
    "name": "Passage 2 The Women Scientists of Bologna",
    "title": "Passage 2 The Women Scientists of Bologna",
    "slug": "passage-2-the-women-scientists-of-bologna",
    "filename": "Passage 2 The Women Scientists of Bologna.html",
    "category": "Passage 2",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "86",
    "name": "Passage 2 Why Do Singers Lose Their Voices",
    "title": "Passage 2 Why Do Singers Lose Their Voices",
    "slug": "passage-2-why-do-singers-lose-their-voices",
    "filename": "Passage 2 Why Do Singers Lose Their Voices.html",
    "category": "Passage 2",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "87",
    "name": "Passage 3 - Age-proofing our brains",
    "title": "Passage 3 - Age-proofing our brains",
    "slug": "passage-3-age-proofing-our-brains",
    "filename": "Passage 3 - Age-proofing our brains.html",
    "category": "Passage 3",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "88",
    "name": "Passage 3 - The Quiet Rehabilitation of Boredom",
    "title": "Passage 3 - The Quiet Rehabilitation of Boredom",
    "slug": "passage-3-the-quiet-rehabilitation-of-boredom",
    "filename": "Passage 3 - The Quiet Rehabilitation of Boredom.html",
    "category": "Passage 3",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "89",
    "name": "Passage 3 Are We Born Able to Imitate",
    "title": "Passage 3 Are We Born Able to Imitate",
    "slug": "passage-3-are-we-born-able-to-imitate",
    "filename": "Passage 3 Are We Born Able to Imitate.html",
    "category": "Passage 3",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "90",
    "name": "Passage 3 How a Prehistoric Predator Took to the Skies",
    "title": "Passage 3 How a Prehistoric Predator Took to the Skies",
    "slug": "passage-3-how-a-prehistoric-predator-took-to-the-skies",
    "filename": "Passage 3 How a Prehistoric Predator Took to the Skies.html",
    "category": "Passage 3",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "91",
    "name": "Passage 3 Is Artificial Intelligence a Threat",
    "title": "Passage 3 Is Artificial Intelligence a Threat",
    "slug": "passage-3-is-artificial-intelligence-a-threat",
    "filename": "Passage 3 Is Artificial Intelligence a Threat.html",
    "category": "Passage 3",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "92",
    "name": "Passage 3 Science and Filmmaking",
    "title": "Passage 3 Science and Filmmaking",
    "slug": "passage-3-science-and-filmmaking",
    "filename": "Passage 3 Science and Filmmaking.html",
    "category": "Passage 3",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "93",
    "name": "Passage 3 Science in the Kitchen",
    "title": "Passage 3 Science in the Kitchen",
    "slug": "passage-3-science-in-the-kitchen",
    "filename": "Passage 3 Science in the Kitchen.html",
    "category": "Passage 3",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "94",
    "name": "Passage 3 Sir Francis Ronalds",
    "title": "Passage 3 Sir Francis Ronalds",
    "slug": "passage-3-sir-francis-ronalds",
    "filename": "Passage 3 Sir Francis Ronalds.html",
    "category": "Passage 3",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "95",
    "name": "Passage 3 Some Views on the Use of Headphones",
    "title": "Passage 3 Some Views on the Use of Headphones",
    "slug": "passage-3-some-views-on-the-use-of-headphones",
    "filename": "Passage 3 Some Views on the Use of Headphones.html",
    "category": "Passage 3",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "96",
    "name": "Passage 3 Tasmanias Museum of Old and New Art",
    "title": "Passage 3 Tasmanias Museum of Old and New Art",
    "slug": "passage-3-tasmanias-museum-of-old-and-new-art",
    "filename": "Passage 3 Tasmanias Museum of Old and New Art.html",
    "category": "Passage 3",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "97",
    "name": "Passage 3 The art of deception",
    "title": "Passage 3 The art of deception",
    "slug": "passage-3-the-art-of-deception",
    "filename": "Passage 3 The art of deception.html",
    "category": "Passage 3",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "98",
    "name": "Passage 3 The Long Road to Artificial Intelligence",
    "title": "Passage 3 The Long Road to Artificial Intelligence",
    "slug": "passage-3-the-long-road-to-artificial-intelligence",
    "filename": "Passage 3 The Long Road to Artificial Intelligence.html",
    "category": "Passage 3",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "99",
    "name": "Passage 3 The Psychology of New Product Adoption",
    "title": "Passage 3 The Psychology of New Product Adoption",
    "slug": "passage-3-the-psychology-of-new-product-adoption",
    "filename": "Passage 3 The Psychology of New Product Adoption.html",
    "category": "Passage 3",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "100",
    "name": "Passage 3 Thinking for Themselves",
    "title": "Passage 3 Thinking for Themselves",
    "slug": "passage-3-thinking-for-themselves",
    "filename": "Passage 3 Thinking for Themselves.html",
    "category": "Passage 3",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "101",
    "name": "Passage 3 Understanding the Lessons of the Past",
    "title": "Passage 3 Understanding the Lessons of the Past",
    "slug": "passage-3-understanding-the-lessons-of-the-past",
    "filename": "Passage 3 Understanding the Lessons of the Past.html",
    "category": "Passage 3",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "102",
    "name": "Passage 3 Yawning",
    "title": "Passage 3 Yawning",
    "slug": "passage-3-yawning",
    "filename": "Passage 3 Yawning.html",
    "category": "Passage 3",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "103",
    "name": "Passage_1_Transport_and_Transport_Systems_During_the_Roman_Empire",
    "title": "Passage_1_Transport_and_Transport_Systems_During_the_Roman_Empire",
    "slug": "passage-1-transport-and-transport-systems-during-the-roman-empire",
    "filename": "Passage_1_Transport_and_Transport_Systems_During_the_Roman_Empire.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "104",
    "name": "Passage_2_Can_a_Global_Database_of_Fossils_Help_Us_Predict_Biodiversity",
    "title": "Passage_2_Can_a_Global_Database_of_Fossils_Help_Us_Predict_Biodiversity",
    "slug": "passage-2-can-a-global-database-of-fossils-help-us-predict-biodiversity",
    "filename": "Passage_2_Can_a_Global_Database_of_Fossils_Help_Us_Predict_Biodiversity.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "105",
    "name": "PR3_Part1_T_Rex_Hunter_",
    "title": "PR3_Part1_T_Rex_Hunter_",
    "slug": "pr3-part1-t-rex-hunter",
    "filename": "PR3_Part1_T_Rex_Hunter_.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "106",
    "name": "Preserving Gardens (1)",
    "title": "Preserving Gardens (1)",
    "slug": "preserving-gardens-1",
    "filename": "Preserving Gardens (1).html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "107",
    "name": "Preserving_Gardens",
    "title": "Preserving_Gardens",
    "slug": "preserving-gardens",
    "filename": "Preserving_Gardens.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "108",
    "name": "Reading 13 reports from 19",
    "title": "Reading 13 reports from 19",
    "slug": "reading-13-reports-from-19",
    "filename": "Reading 13 reports from 19.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "109",
    "name": "Reading Mock",
    "title": "Reading Mock",
    "slug": "reading-mock",
    "filename": "Reading Mock .html",
    "category": "Mock",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "110",
    "name": "Rebranding_Art_Museums",
    "title": "Rebranding_Art_Museums",
    "slug": "rebranding-art-museums",
    "filename": "Rebranding_Art_Museums.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "111",
    "name": "Science_and_Filmmaking_",
    "title": "Science_and_Filmmaking_",
    "slug": "science-and-filmmaking",
    "filename": "Science_and_Filmmaking_.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "112",
    "name": "Sign Baby Sign (1)",
    "title": "Sign Baby Sign (1)",
    "slug": "sign-baby-sign-1",
    "filename": "Sign Baby Sign (1).html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "113",
    "name": "Skyscraper_Farming_",
    "title": "Skyscraper_Farming_",
    "slug": "skyscraper-farming",
    "filename": "Skyscraper_Farming_.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "114",
    "name": "Socotra_Island",
    "title": "Socotra_Island",
    "slug": "socotra-island",
    "filename": "Socotra_Island.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "115",
    "name": "Socotra_Island_1",
    "title": "Socotra_Island_1",
    "slug": "socotra-island-1",
    "filename": "Socotra_Island_1.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "116",
    "name": "Sorry_Who_Are_You",
    "title": "Sorry_Who_Are_You",
    "slug": "sorry-who-are-you",
    "filename": "Sorry_Who_Are_You.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "117",
    "name": "Sweet_Trouble",
    "title": "Sweet_Trouble",
    "slug": "sweet-trouble",
    "filename": "Sweet_Trouble.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "118",
    "name": "The development of the silk industry (1)",
    "title": "The development of the silk industry (1)",
    "slug": "the-development-of-the-silk-industry-1",
    "filename": "The development of the silk industry (1).html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "119",
    "name": "The Geography of Taste Buds (1)",
    "title": "The Geography of Taste Buds (1)",
    "slug": "the-geography-of-taste-buds-1",
    "filename": "The Geography of Taste Buds (1).html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "120",
    "name": "The History of Ice Cream (1)",
    "title": "The History of Ice Cream (1)",
    "slug": "the-history-of-ice-cream-1",
    "filename": "The History of Ice Cream (1).html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "121",
    "name": "The Internal Body Clock (1)",
    "title": "The Internal Body Clock (1)",
    "slug": "the-internal-body-clock-1",
    "filename": "The Internal Body Clock (1).html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "122",
    "name": "The Rise of Eco-tourism",
    "title": "The Rise of Eco-tourism",
    "slug": "the-rise-of-eco-tourism",
    "filename": "The Rise of Eco-tourism.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "123",
    "name": "The Seed Hunters",
    "title": "The Seed Hunters",
    "slug": "the-seed-hunters",
    "filename": "The Seed Hunters.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "124",
    "name": "The Strange World of Sight",
    "title": "The Strange World of Sight",
    "slug": "the-strange-world-of-sight",
    "filename": "The Strange World of Sight.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "125",
    "name": "The_Art_of_Deception",
    "title": "The_Art_of_Deception",
    "slug": "the-art-of-deception",
    "filename": "The_Art_of_Deception.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "126",
    "name": "The_History_of_the_Potato",
    "title": "The_History_of_the_Potato",
    "slug": "the-history-of-the-potato",
    "filename": "The_History_of_the_Potato.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "127",
    "name": "The_Silk_Industry",
    "title": "The_Silk_Industry",
    "slug": "the-silk-industry",
    "filename": "The_Silk_Industry.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "128",
    "name": "The_University_of_Life",
    "title": "The_University_of_Life",
    "slug": "the-university-of-life",
    "filename": "The_University_of_Life.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "129",
    "name": "Why good ideas fail",
    "title": "Why good ideas fail",
    "slug": "why-good-ideas-fail",
    "filename": "Why good ideas fail.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  },
  {
    "id": "130",
    "name": "William_Gilbert_and_Magnetism",
    "title": "William_Gilbert_and_Magnetism",
    "slug": "william-gilbert-and-magnetism",
    "filename": "William_Gilbert_and_Magnetism.html",
    "category": "Academic",
    "difficulty": "Medium",
    "duration": 20,
    "questionCount": 13
  }
];

export function getReadingTest(slug: string): ReadingTest | undefined {
  return READING_TESTS.find(t => t.slug === slug);
}
